name: Issue Template
description: Standard template for new issues
title: "[Issue]: "
labels: []
assignees: []

body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Briefly describe the issue or feature request.
      placeholder: Provide a concise summary of the issue.
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: Define the conditions that must be met for this issue to be considered complete.
      placeholder: List clear, testable acceptance criteria. Given/When/Then format is recommended.
    validations:
      required: true